# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

try:
    import image_pb2 as image__pb2
except ImportError:
    from functions.grpc_functions import image_pb2 as image__pb2


class GenerateImagesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateLevelImage = channel.unary_unary(
                '/imageGenerator.GenerateImages/GenerateLevelImage',
                request_serializer=image__pb2.LevelData.SerializeToString,
                response_deserializer=image__pb2.Image.FromString,
                )


class GenerateImagesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateLevelImage(self, request, context):
        """Generate the Image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerateImagesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateLevelImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateLevelImage,
                    request_deserializer=image__pb2.LevelData.FromString,
                    response_serializer=image__pb2.Image.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageGenerator.GenerateImages', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GenerateImages(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateLevelImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageGenerator.GenerateImages/GenerateLevelImage',
            image__pb2.LevelData.SerializeToString,
            image__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
