# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='imageGenerator',
  syntax='proto3',
  serialized_options=b'Z\021.;image_generator',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bimage.proto\x12\x0eimageGenerator\"\x16\n\x05Image\x12\r\n\x05Image\x18\x01 \x01(\x0c\"\xb2\x01\n\tLevelData\x12\x0b\n\x03\x45XP\x18\x01 \x01(\x02\x12\x13\n\x0bRequiredEXP\x18\x02 \x01(\x02\x12\x10\n\x08Position\x18\x03 \x01(\t\x12\x10\n\x08UserName\x18\x04 \x01(\t\x12\x12\n\nServerName\x18\x05 \x01(\t\x12\x10\n\x08RankCard\x18\x06 \x01(\t\x12\x14\n\x0cNextRoleName\x18\x07 \x01(\t\x12\x12\n\nNextRoleId\x18\x08 \x01(\x03\x12\x0f\n\x07profile\x18\t \x01(\x0c\x32Z\n\x0eGenerateImages\x12H\n\x12GenerateLevelImage\x12\x19.imageGenerator.LevelData\x1a\x15.imageGenerator.Image\"\x00\x42\x13Z\x11.;image_generatorb\x06proto3'
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='imageGenerator.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Image', full_name='imageGenerator.Image.Image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=53,
)


_LEVELDATA = _descriptor.Descriptor(
  name='LevelData',
  full_name='imageGenerator.LevelData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='EXP', full_name='imageGenerator.LevelData.EXP', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RequiredEXP', full_name='imageGenerator.LevelData.RequiredEXP', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Position', full_name='imageGenerator.LevelData.Position', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UserName', full_name='imageGenerator.LevelData.UserName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ServerName', full_name='imageGenerator.LevelData.ServerName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RankCard', full_name='imageGenerator.LevelData.RankCard', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NextRoleName', full_name='imageGenerator.LevelData.NextRoleName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NextRoleId', full_name='imageGenerator.LevelData.NextRoleId', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profile', full_name='imageGenerator.LevelData.profile', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=234,
)

DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['LevelData'] = _LEVELDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:imageGenerator.Image)
  })
_sym_db.RegisterMessage(Image)

LevelData = _reflection.GeneratedProtocolMessageType('LevelData', (_message.Message,), {
  'DESCRIPTOR' : _LEVELDATA,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:imageGenerator.LevelData)
  })
_sym_db.RegisterMessage(LevelData)


DESCRIPTOR._options = None

_GENERATEIMAGES = _descriptor.ServiceDescriptor(
  name='GenerateImages',
  full_name='imageGenerator.GenerateImages',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=236,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateLevelImage',
    full_name='imageGenerator.GenerateImages.GenerateLevelImage',
    index=0,
    containing_service=None,
    input_type=_LEVELDATA,
    output_type=_IMAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENERATEIMAGES)

DESCRIPTOR.services_by_name['GenerateImages'] = _GENERATEIMAGES

# @@protoc_insertion_point(module_scope)
